In [33]:
%matplotlib inline

import tensorflow as tf
import numpy as np

import os
import sys

sess = tf.InteractiveSession()

In [39]:
# VGG Model

def conv_layer(weights, bias):
    def _make_layer(input):
        conv = tf.nn.conv2d(input, tf.constant(weights), strides=[1, 1, 1, 1],
                            padding='SAME')
        return tf.nn.bias_add(conv, bias)
    return _make_layer

In [38]:
x_data = np.ones([3., 3.]).astype("float32")
x_data = np.reshape(x_data, [1, 3, 3, 1])

w = np.ones([2,2])
w = tf.cast(tf.reshape(w, [2, 2, 1, 1]), "float")

print tf.nn.conv2d(x_data, w, [1, 1, 1, 1], 'SAME').eval()

[[[[ 4.]
   [ 4.]
   [ 2.]]

  [[ 4.]
   [ 4.]
   [ 2.]]

  [[ 2.]
   [ 2.]
   [ 1.]]]]


In [17]:
x_data = np.ones([3., 3.]).astype("float32")
print x_data
print "="*20
x_data = np.reshape(x_data, [1, 3, 3, 1])

w = np.ones([2,2])
print w
print "="*20
w = tf.cast(tf.reshape(w, [2, 2, 1, 1]), "float")
# print w.eval()

print tf.nn.conv2d(x_data, w, [1, 1, 1, 1], 'SAME').eval()
print "="*20