In [1]:
%matplotlib inline

import tensorflow as tf
import numpy as np

import os
import sys

sess = tf.InteractiveSession()

In [3]:
tf.nn.conv2d?

In [39]:
# VGG Model

def conv_layer(weight, bias):
    def _make_layer(input):
        conv = tf.nn.conv2d(input, tf.constant(weights), strides=[1, 1, 1, 1],
                            padding='SAME')
        return tf.nn.bias_add(conv, bias)
    return _make_layer

def conv_layer(weights, bias):
    def _make_layer(input):
        conv = tf.nn.conv2d(input, tf.constant(weights), strides=[1, 1, 1, 1],
                            padding='SAME')
        return tf.nn.bias_add(conv, bias)
    return _make_layer

In [5]:
x_data = np.ones([3., 3.]).astype("float32")
print x_data
print "="*20
x_data = np.reshape(x_data, [1, 3, 3, 1])

w = np.ones([2,2])
print w
print "="*20
w = tf.cast(tf.reshape(w, [2, 2, 1, 1]), "float")
# print w.eval()

print tf.nn.conv2d(x_data, w, [1, 1, 1, 1], 'SAME').eval()
print "="*20

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.]
 [ 1.  1.]]
[[[[ 4.]
   [ 4.]
   [ 2.]]

  [[ 4.]
   [ 4.]
   [ 2.]]

  [[ 2.]
   [ 2.]
   [ 1.]]]]


In [7]:
def pool_layer():
    def _make_layer(input):
        return tf.nn.max_pool(input, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')
    return _make_layer

def add_layer(input_image, layers, func):
    if not layers:
        new = func(input_image)
    else:
        new = func(layers[-1])
    layer.append(new)

In [8]:
data_path = './'

layers = [
    'conv1_1', 'relu1_1', 'conv1_2', 'relu1_2', 'pool1',
    
    'conv2_1', 'relu2_1', 'conv2_2', 'relu2_2', 'pool2',
    
    'conv3_1', 'relu3_1', 'conv3_2', 'relu3_2', 'conv3_3',
    'relu3_3', 'conv3_4', 'relu3_4', 'pool3',
    
    'conv4_1', 'relu4_1', 'conv4_2', 'relu4_2', 'conv4_3',
    'relu4_3', 'conv4_4', 'relu4_4', 'pool4',

    'conv5_1', 'relu5_1', 'conv5_2', 'relu5_2', 'conv5_3',
    'relu5_3', 'conv5_4', 'relu5_4'
]

data = sio.loadmat(data_path)