In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import sys
import threading
import time

import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

In [5]:
from tensorflow.models.rnn import rnn    
from tensorflow.models.rnn.rnn_cell import BasicLSTMCell, LSTMCell, GRUCell

In [9]:
lstm = BasicLSTMCell(lstm_size)
state = tf.zeros([batch_size, lstm.state_size])

In [12]:
print(lstm.state_size)

400


In [20]:
X = [[2,2,4],[1,2,2]]

x, y = tf.split(0, 2, X)
print(x.eval())
print(y.eval())
print("="*30)

x, y, z = tf.split(1, 3, X)
print(x.eval())
print(y.eval())
print(z.eval())

[[2 2 4]]
[[1 2 2]]
[[2]
 [1]]
[[2]
 [2]]
[[4]
 [2]]


In [24]:
input_dim = 100
mem_dim = 150
num_layers = 4
seq_length = 12

batch_size = 20
total_epoch = 12

initializer = tf.random_uniform_initializer(-1,1)

x = tf.placeholder(tf.float32, [seq_length, batch_size, input_dim])
early_stop = tf.placeholder(tf.int32)

inputs = [tf.reshape(i, [batch_size, seq_length]) for i in tf.split(0, seq_length, x)]

cell = LSTMCell(mem_dim, input_dim, initializer=initializer)
initial_state = cell.zero_state(batch_size, tf.float32)

output, state = rnn.rnn(cell, inputs, 
                        initial_state=initial_state, sequence_length=early_stop)

init = tf.initialize_all_variables()
sess.run(init)



ValueError: Dimensions Dimension(162) and Dimension(250) are not compatible

In [ ]:
loss = 0.0

for epoch in range(100):
    output, state = lstm(current_batch, state)
    
    y_ = tf.matmul(output, softmax_w) + softmax_b
    probabilities = tf.nn.softmax(logits)
    loss = loss(probabilities, y_)

In [21]:
LSTMCell?

In [25]:
from tensorflow.models.rnn import rnn_cell
from tensorflow.models.rnn import seq2seq
from tensorflow.models.rnn.ptb import reader

ImportError: No module named ptb