In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import sys
import threading
import time

import tensorflow as tf
import numpy as np

In [3]:
sess = tf.InteractiveSession()

In [4]:
from tensorflow.models.rnn import rnn    
from tensorflow.models.rnn.rnn_cell import BasicLSTMCell, LSTMCell, GRUCell

In [10]:
cell_fn = LSTMCell

In [11]:
X = [[2,2,4],[1,2,2]]

x, y = tf.split(0, 2, X)
print(x.eval())
print(y.eval())
print("="*30)

x, y, z = tf.split(1, 3, X)
print(x.eval())
print(y.eval())
print(z.eval())

[[2 2 4]]
[[1 2 2]]
[[2]
 [1]]
[[2]
 [2]]
[[4]
 [2]]


In [15]:
LSTMCell?

In [13]:
rnn_size = 128 # size of rnn hidden sate
num_layers = 2 # # of layers in RNN
seq_length = 50 # RNN sequence length

batch_size = 50 # minibatch size
num_epochs = 

In [14]:
cell = cell_fn(rnn_size)

TypeError: __init__() takes at least 3 arguments (2 given)

In [ ]:
loss = 0.0

for epoch in range(100):
    output, state = lstm(current_batch, state)
    
    y_ = tf.matmul(output, softmax_w) + softmax_b
    probabilities = tf.nn.softmax(logits)
    loss = loss(probabilities, y_)

In [21]:
LSTMCell?

In [25]:
from tensorflow.models.rnn import rnn_cell
from tensorflow.models.rnn import seq2seq
from tensorflow.models.rnn.ptb import reader

ImportError: No module named ptb